name: 'Terraform'

on:
  workflow_call:
    inputs:
      terraform-version:
        required: false
        type: string
        default: latest
      directory:
        required: false
        type: string
        default: '.'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
    - run: terraform -chdir=${{ inputs.directory }} fmt -check -diff -recursive
    - run: terraform -chdir=${{ inputs.directory }} init -backend=false
    - run: terraform -chdir=${{ inputs.directory }} validate
